#!/usr/bin/env bash

section_start() {
  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
  echo "${1}"
}

reinstall_dotfiles() {
  rm -rf ~/.{local/bin,npm,nvm,zinit,go/bin,config/composer/vendor,nvim,config/nvim}
  cd ~/.dotfiles && ./setup.sh
}

install_arch_packages() {
  echo 'Enabling the AUR...'
  sudo sed -Ei '/EnableAUR/s/^#//' /etc/pamac.conf

  PACKAGES=(
    # General
    redshift
    ulauncher
    variety
    bitwarden
    plank
    spotify-launcher
    spotifyd
    pandoc
    texlive-basic
    texlive-latex
    texlive-latexrecommended
    texlive-pictures
    texlive-latexextra
    texlive-fontsrecommended

    # Social
    discord
    caprine
    whatsapp-for-linux

    # Work
    microsoft-edge-stable-bin
    clickup
    zoom

    # Dev
    alacritty
    ghostty
    tmux
    github-cli
    go
    rustup
    nginx
    mailpit
    mariadb
    php-legacy
    php-legacy-fpm
    php-legacy-gd
    php-legacy-imagick
    php-legacy-sodium
    php-legacy-sqlite
    php-legacy-tidy
    php-legacy-xdebug
    php-legacy-xsl
    python
    python-pip
    python-pipx

    # Fonts
    noto-fonts-emoji
    ttf-anonymouspro-nerd
    ttf-dejavu-nerd
    ttf-firacode-nerd
    ttf-go-nerd
    ttf-hack-nerd
    ttf-jetbrains-mono-nerd
    ttf-liberation-mono-nerd
    ttf-sourcecodepro-nerd
    ttf-terminus-nerd

    # IDE
    neovim
    lua-language-server
    shellcheck
    hadolint-bin

    # System
    vim
    tldr
    git
    jq
    ripgrep
    exa
    fd
    git-delta
    xsel
    xclip
    imagemagick
    dnsutils
    bat
  )

  # shellcheck disable=2046
  sudo pamac install --no-confirm --no-upgrade $(
    IFS=' '
    echo "${PACKAGES[*]}"
  ) "$@"
}

install_wsl_packages() {
  add_wslu_ppa
  add_eza_ppa
  add_php_ppa
  add_gh_cli_ppa

  PACKAGES=(
    # Text processing
    pandoc
    texlive-latex-base
    texlive-latex-extra
    texlive-latex-recommended
    texlive-fonts-recommended
    texlive-fonts-extra

    # Dev
    mariadb-server
    tmux
    golang-go
    python3
    python3-pip
    pipx

    # Fonts
    fonts-noto-color-emoji
    fonts-firacode
    fonts-hack
    fonts-jetbrains-mono

    # IDE
    shellcheck

    # System
    cmake
    libnss3-tools
    vim
    tldr
    git
    gh
    gpg
    jq
    ripgrep
    eza
    fd-find
    fzf
    xsel
    xclip
    imagemagick
    dnsutils
    bat
    zsh
    wslu
  )

  PHP_PACKAGES=(
    bcmath
    bz2
    cli
    common
    curl
    fpm
    gd
    gmp
    intl
    mbstring
    mysql
    opcache
    readline
    soap
    tidy
    xdebug
    xml
    xsl
    zip
  )
  PHP_VERSIONS=(8.1 8.2)
  for VERSION in "${PHP_VERSIONS[@]}"; do
    mapfile -t PHP_COMBINED_PACKAGES < <(printf '%s\n' "${PHP_PACKAGES[@]}" | sed "s/^/php${VERSION}-/")
    PACKAGES=( "${PACKAGES[@]}" "${PHP_COMBINED_PACKAGES[@]}" )
  done

  sudo add-apt-repository ppa:longsleep/golang-backports -y

  sudo apt update

  # shellcheck disable=2046
  sudo apt install -y "${PACKAGES[@]}"

  install_rustup
  install_neovim
  install_git_delta
  # ensure fd is available
  ln -sf "$(which fdfind)" ~/.local/bin/fd
}

setup_arch_services() {
  SERVICES=(
    nginx
    mariadb
    php-fpm
  )

  # shellcheck disable=2046
  sudo systemctl start $(
    IFS=' '
    echo "${SERVICES[*]}"
  )
  # shellcheck disable=2046
  sudo systemctl enable $(
    IFS=' '
    echo "${SERVICES[*]}"
  )
}

install_nvm() {
  # shellcheck disable=SC2155
  export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.config/nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" && \
    mkdir -p "${NVM_DIR}" && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
}

install_rustup() {
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
}

install_neovim() {
  local DIRNAME='nvim-linux-x86_64'
  local FILENAME="${DIRNAME}.tar.gz"
  local OUTPUT_PATH="/tmp/${FILENAME}"

  curl -L "https://github.com/neovim/neovim/releases/latest/download/${FILENAME}" --output "${OUTPUT_PATH}"

  mkdir -p ~/.local/bin

  [ -e ~/.local/bin/nvim ] && rm ~/.local/bin/nvim

  sudo rm -rf /opt/nvim
  sudo rm -rf /opt/neovim

  sudo tar -C /opt -xzf "${OUTPUT_PATH}"

  ln -s "/opt/${DIRNAME}/bin/nvim" ~/.local/bin/nvim
}

gh_get_latest_tag() {
  if [[ -z "${1}" ]]; then
    echo 'No repo provided' >&2
    return 1
  fi

  TIMEOUT=90
  curl --silent --location --max-time "${TIMEOUT}" "https://api.github.com/repos/${1}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
}

install_git_delta() {
  REPO='dandavison/delta'
  VERSION="$(gh_get_latest_tag "${REPO}")"
  VERSION="${VERSION:-0.16.5}"
  FILE="git-delta_${VERSION}_amd64.deb"
  curl -LO "https://github.com/${REPO}/releases/latest/download/${FILE}" && sudo dpkg -i "${FILE}" && rm "${FILE}"
}

install_node_packages() {
  if [[ ! -d "${NVM_DIR}" ]] || [[ ! -d "${HOME}/.nvm" ]]; then
    install_nvm
  fi

  PACKAGES=(
    @ansible/ansible-language-server
    @fsouza/prettierd
    @tailwindcss/language-server
    @vue/language-server
    bash-language-server
    blade-formatter
    doctoc
    eslint_d
    fast-cli
    intelephense
    lighthouse
    markdownlint
    markdownlint-cli
    speed-test
    stylelint
    stylelint-config-prettier
    stylelint-lsp
    typescript
    typescript-language-server
    vscode-langservers-extracted
    yaml-language-server
  )

  # shellcheck disable=2046
  yarn global add $(
    IFS=' '
    echo "${PACKAGES[*]}"
  ) "$@"
}

install_go_packages() {
  PACKAGES=(
    github.com/rhysd/actionlint/cmd/actionlint@latest
    golang.org/x/tools/gopls@latest
    mvdan.cc/sh/v3/cmd/shfmt@latest
    mvdan.cc/xurls/v2/cmd/xurls@latest
  )

  for P in "${PACKAGES[@]}"; do
    go install "${P}" "$@"
  done
}

install_composer_packages() {
  PACKAGES=(
    cpriego/valet-linux:dev-master
    wp-cli/wp-cli-bundle
    itinerisltd/itineris-wp-coding-standards
  )

  # shellcheck disable=2046
  composer global require $(
    IFS=' '
    echo "${PACKAGES[*]}"
  ) "$@"
}

install_pip_packages() {
  PACKAGES=(
    csvkit
    yamllint
  )

  for P in "${PACKAGES[@]}"; do
    pipx install "${P}" "$@"
  done
}

install_cargo_packages() {
  PACKAGES=(
    stylua
  )

  # shellcheck disable=2046
  cargo install $(
    IFS=' '
    echo "${PACKAGES[*]}"
  ) "$@"
}

post_install_packages() {
  section_start 'Post package install'

  # shellcheck disable=2016
  echo 'Running `mariadb-install-db`'
  sudo mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

  echo 'Enabling PHP extensions'
  sudo sed -Ei '/^;extension=mysqli/s/^;//' /etc/php7/php.ini
  sudo sed -Ei '/^;extension=gd/s/^;//' /etc/php7/php.ini

  echo 'Installing `spotify-tui'
  mkdir "${HOME}/.rustup"
  rustup default stable
  pamac install --no-confirm --no-upgrade spotify-tui
}

post_setup_arch_services() {
  section_start 'Post setup arch services'

  setup_mysql
}

setup_arch_system_emoji_support() {
  sudo pamac install noto-fonts-emoji
  sudo cp ~/.dotfiles/templates/fonts-local.conf /etc/fonts/local.conf
}

add_wslu_ppa() {
  sudo add-apt-repository ppa:wslutilities/wslu -y
}

add_eza_ppa() {
  sudo mkdir -p /etc/apt/keyrings
  wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
  echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
  sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
}

add_php_ppa() {
  sudo add-apt-repository ppa:ondrej/php -y
}

add_gh_cli_ppa() {
  # shellcheck disable=SC2086,SC2002
  (type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) && \
    sudo mkdir -p -m 755 /etc/apt/keyrings && \
    out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg && \
    cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg >/dev/null && \
    sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg && \
    sudo mkdir -p -m 755 /etc/apt/sources.list.d && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
}

setup_mysql() {
  # shellcheck disable=2016
  echo 'Running `mysql_secure_installation`'
  sudo mysql_secure_installation

  echo -e 'Creating wp mysql user'
  sudo mysql -e "CREATE USER IF NOT EXISTS 'wp'@'localhost' IDENTIFIED BY 'wp'"
  sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'wp'@'localhost' WITH GRANT OPTION"
  sudo mysql -e "FLUSH PRIVILEGES"
}

post_setup_wsl_services() {
  setup_mysql
}
