# Zinit
source ~/.zinit/bin/zinit.zsh

export PATH="$HOME/bin:/usr/local/bin:$PATH:$HOME/.local/bin"

# Homebrew
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# Load sensitive variables such as credentials and tokens
if [ -f ~/.shell_env ]; then
  . ~/.shell_env
fi

# Set local and remote editor
export EDITOR='vim'

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Node
export NVM_SYMLINK_CURRENT=true
export NVM_AUTO_USE=true

# Plugins
zinit ice wait"0b" lucid atload'bindkey "$terminfo[kcuu1]" history-substring-search-up; bindkey "$terminfo[kcud1]" history-substring-search-down'
zinit light zsh-users/zsh-history-substring-search
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
zinit ice wait"0a" lucid atload"_zsh_autosuggest_start"
zinit light zsh-users/zsh-autosuggestions
zinit ice wait"0b" lucid blockf
zinit light zsh-users/zsh-completions
zinit ice wait"0c" lucid atinit"zpcompinit;zpcdreplay"
zinit light zdharma/fast-syntax-highlighting
zinit ice wait"1" lucid
zinit light lukechilds/zsh-nvm
zinit snippet OMZP::npm

# Theme
zinit light denysdovhan/spaceship-prompt

# Spaceship Prompt
SPACESHIP_TIME_SHOW=true
SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  package       # Package version
  node          # Node.js section
  php           # PHP section
  venv          # virtualenv section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

SPACESHIP_RPROMPT_ORDER=(
  time          # Time stampts section
)

# Setup history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=1000
setopt SHARE_HISTORY

autoload -U compinit && compinit
zmodload -i zsh/complist
compdef __git_branch_names gpDo

# Trellis virtualenv shell integration
eval "$(trellis shell-init zsh)"

# iTerm2 shell integration
if [[ "${OSTYPE:0:6}" == "darwin" && -f ~/.iterm2_shell_integration.zsh ]]; then
  source ~/.iterm2_shell_integration.zsh
fi

# Load aliases
if [ -f ~/.shell_aliases ]; then
  . ~/.shell_aliases
fi

# Key bindings
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
