export PATH="$HOME/bin:/usr/local/bin:$PATH:$(yarn global bin):$HOME/.local/bin"

# Load sensitive variables such as credentials and tokens
if [ -f ~/.env ]; then
  . ~/.env
fi

# Set local and remote editor
export EDITOR='vim'

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Load aliases
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# Key bindings
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export NVM_AUTO_USE=true

# Fix VTC issue for Ubuntu
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
	source /etc/profile.d/vte-2.91.sh
fi

setopt promptsubst

source ~/.zplug/init.zsh

# Plugins
zplug "zdharma/fast-syntax-highlighting", defer:2
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "plugins/history-substring-search", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
zplug "lukechilds/zsh-nvm"
zplug "plugins/npm", from:oh-my-zsh
zplug "plugins/composer", from:oh-my-zsh
zplug "plugins/encode64", from:oh-my-zsh
zplug "plugins/yarn", from:oh-my-zsh
zplug "g-plane/zsh-yarn-autocompletions", hook-build:"./zplug.zsh", defer:2

# Theme
zplug denysdovhan/spaceship-prompt, use:spaceship.zsh, from:github, as:theme

# Load
zplug load

SPACESHIP_TIME_SHOW=true

# Spaceship Prompt
SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  package       # Package version
  node          # Node.js section
  php           # PHP section
  venv          # virtualenv section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

SPACESHIP_RPROMPT_ORDER=(
  time          # Time stampts section
)

# Setup history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=1000
setopt SHARE_HISTORY

autoload -U compinit && compinit
zmodload -i zsh/complist
compdef __git_branch_names gpDo

# Trellis virtualenv shell integration
eval "$(trellis shell-init zsh)"
