export PATH="$HOME/bin:/usr/local/bin:$PATH:$HOME/.local/bin"

# Homebrew
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# Load sensitive variables such as credentials and tokens
if [ -f ~/.env ]; then
  . ~/.env
fi

# Set local and remote editor
export EDITOR='vim'

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Key bindings
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

if [[ "${OSTYPE:0:6}" = "darwin" ]] ; then
  export ZPLUG_HOME=/usr/local/opt/zplug
  source $ZPLUG_HOME/init.zsh
elif [[ "${OSTYPE:0:6}" = "linux" ]] ; then
  source ~/.zplug/init.zsh
fi

# Plugins
zplug "zdharma/fast-syntax-highlighting", defer:2
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "plugins/history-substring-search", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
zplug "lukechilds/zsh-nvm"
zplug "plugins/npm", from:oh-my-zsh
zplug "plugins/composer", from:oh-my-zsh
zplug "plugins/encode64", from:oh-my-zsh
zplug "plugins/yarn", from:oh-my-zsh
zplug "g-plane/zsh-yarn-autocompletions", hook-build:"./zplug.zsh", defer:2

# Theme
zplug denysdovhan/spaceship-prompt, use:spaceship.zsh, from:github, as:theme

# Load
zplug load

# Node
export NVM_AUTO_USE=true
export PATH="$PATH:$(yarn global bin)"

# Spaceship Prompt
SPACESHIP_TIME_SHOW=true
SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  package       # Package version
  node          # Node.js section
  php           # PHP section
  venv          # virtualenv section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

SPACESHIP_RPROMPT_ORDER=(
  time          # Time stampts section
)

# Setup history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=1000
setopt SHARE_HISTORY

autoload -U compinit && compinit
zmodload -i zsh/complist
compdef __git_branch_names gpDo

# Trellis virtualenv shell integration
eval "$(trellis shell-init zsh)"

# Load aliases
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi
